Repository Volgarenok/spbspu-labs-2025-aads-classes-b, pull requests merged in 2025-03, with the labels that each got.

#29 kizhin.evgeniy/K4
  kizhin.evgeniy/K4/forward-list.hpp
Labels: 2 out of 2, fine

#23 karnauhova.alexandra/K4
  karnauhova.alexandra/K4/main.cpp
Labels: 2 out of 2, fine

#26 kiselev.sergey/K4
  kiselev.sergey/K4/main.cpp
Labels: 2 out of 2, fine

#19 duhanina.alina/K4
  duhanina.alina/K4/main.cpp
Labels: 2 out of 2, fine

#18 averenkov.eugene/K4
  averenkov.eugene/K4/list.hpp
  averenkov.eugene/K4/main.cpp
Labels: 2 out of 2, fine

#17 demehin.maxim/K4
  demehin.maxim/K4/main.cpp
Labels: 2 out of 2, fine

#5 zholobov.oleg/K2
  zholobov.oleg/K2/main.cpp
Labels: 1 out of 2, fine

#16 dribas.sergey/K4
  dribas.sergey/K4/main.cpp
Labels: 2 out of 2, fine

#15 gavrilova.polina/K2
  gavrilova.polina/K2/main.cpp
Labels: 2 out of 2, fine

#24 Brevnov.nikita/k4
  brevnov.nikita/K4/main.cpp
Labels: 2 out of 2, fine

#14 Bocharov.egor/K2
  bocharov.egor/K2/main.cpp
Labels: 2 out of 2, trash

#20 zholobov.oleg/K4
  zholobov.oleg/K4/main.cpp
Labels: 1 out of 2, trash

#21 dirti.aldyn/K4
  dirti.aldyn/K2/main.cpp
  dirti.aldyn/K4/main.cpp
Labels: 1 out of 2, trash
