Repository Volgarenok/spbspu-labs-2025-aads-classes-b, pull requests merged in 2025-02, with the labels that each got.

#10 kiselev.sergey/K2
  kiselev.sergey/K2/main.cpp
Labels: 2 out of 2, actor, fine

#11 kizhin.evgeniy/K2
  kizhin.evgeniy/K2/forward-list.cpp
  kizhin.evgeniy/K2/forward-list.hpp
  kizhin.evgeniy/K2/main.cpp
Labels: 2 out of 2, fine

#1 demehin.maxim/K2
  demehin.maxim/K2/main.cpp
Labels: 2 out of 2

#7 karnauhova.alexandra/K2
  karnauhova.alexandra/K2/main.cpp
Labels: 2 out of 2, actor, fine

#2 dribas.sergey/K2
  dribas.sergey/K2/list.cpp
  dribas.sergey/K2/list.hpp
  dribas.sergey/K2/main.cpp
Labels: 2 out of 2, actor, fine

#4 averenkov.eugene/K2
  averenkov.eugene/K2/main.cpp
Labels: 2 out of 2, fine

#12 evstyunichev.konstantin/K2
  evstyunichev.konstantin/K2/main.cpp
Labels: 2 out of 2, fine

#6 duhanina.alina/K2
  duhanina.alina/K2/main.cpp
Labels: 2 out of 2, fine

#25 kizhin.evgeniy/K4
  kizhin.evgeniy/K4/forward-list.hpp
  kizhin.evgeniy/K4/io-utils.hpp
  kizhin.evgeniy/K4/main.cpp
  kizhin.evgeniy/K4/parse-args.cpp
  kizhin.evgeniy/K4/parse-args.hpp
Labels: 2 out of 2, fine
